#!/usr/bin/env python3

import argparse
import getpass
import os
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from pathlib import Path
import xml.etree.ElementTree as ET

import requests
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


def api_request(host, params, verify_ssl=False):
    """
    Make a PAN-OS API request.
    """

    url = f"https://{host}/api/"

    response = requests.post(
        url,
        params=params,
        verify=verify_ssl,
        timeout=180,
    )

    response.raise_for_status()

    try:
        root = ET.fromstring(response.content)
    except ET.ParseError:
        raise RuntimeError(
            f"{host}: invalid XML returned:\n"
            f"{response.text[:1000]}"
        )

    if root.attrib.get("status") != "success":
        msg = root.findtext(".//msg")

        raise RuntimeError(
            f"{host}: API error: "
            f"{msg or response.text[:1000]}"
        )

    return response.content, root


def generate_api_key(host, username, password, verify_ssl=False):

    params = {
        "type": "keygen",
        "user": username,
        "password": password,
    }

    _, root = api_request(
        host,
        params,
        verify_ssl,
    )

    key = root.findtext(".//key")

    if not key:
        raise RuntimeError(
            f"{host}: no API key returned"
        )

    return key


def get_full_config(host, api_key, verify_ssl=False):

    params = {
        "type": "config",
        "action": "show",
        "xpath": "/config",
        "key": api_key,
    }

    # Use the API key in the request itself.
    url = f"https://{host}/api/"

    response = requests.post(
        url,
        params=params,
        verify=verify_ssl,
        timeout=300,
    )

    response.raise_for_status()

    try:
        root = ET.fromstring(response.content)
    except ET.ParseError:
        raise RuntimeError(
            f"{host}: invalid XML returned"
        )

    if root.attrib.get("status") != "success":
        msg = root.findtext(".//msg")

        raise RuntimeError(
            f"{host}: API error: "
            f"{msg or response.text[:1000]}"
        )

    return response.content


def sanitize_filename(name):

    return "".join(
        c if c.isalnum() or c in "-_." else "_"
        for c in name
    )


def read_firewall_list(filename):

    firewalls = []

    with open(filename, "r") as f:

        for line_number, line in enumerate(f, 1):

            line = line.strip()

            if not line:
                continue

            if line.startswith("#"):
                continue

            parts = line.split("|")

            if len(parts) != 3:
                print(
                    f"WARNING: skipping malformed line "
                    f"{line_number}: {line}",
                    file=sys.stderr,
                )
                continue

            hostname, ip, serial = parts

            firewalls.append({
                "hostname": hostname,
                "ip": ip,
                "serial": serial,
            })

    return firewalls


def backup_firewall(
    firewall,
    username,
    password,
    output_dir,
    date_string,
    verify_ssl=False,
):
    hostname = firewall["hostname"]
    ip = firewall["ip"]
    serial = firewall["serial"]

    try:

        print(
            f"[{hostname}] Generating API key..."
        )

        api_key = generate_api_key(
            ip,
            username,
            password,
            verify_ssl,
        )

        print(
            f"[{hostname}] Pulling full config..."
        )

        config = get_full_config(
            ip,
            api_key,
            verify_ssl,
        )

        filename = (
            f"{sanitize_filename(hostname)}-"
            f"{date_string}.xml"
        )

        output_file = output_dir / filename

        output_file.write_bytes(config)

        return {
            "success": True,
            "hostname": hostname,
            "ip": ip,
            "serial": serial,
            "file": output_file,
        }

    except Exception as exc:

        return {
            "success": False,
            "hostname": hostname,
            "ip": ip,
            "serial": serial,
            "error": str(exc),
        }


def main():

    parser = argparse.ArgumentParser(
        description="Pull XML configs directly from PAN-OS firewalls."
    )

    parser.add_argument(
        "firewall_file",
        help="firewalls-YYYY-MM-DD.txt generated by script 1",
    )

    parser.add_argument(
        "--username",
        default=os.environ.get("PAN_USER"),
        help="Firewall admin username or PAN_USER",
    )

    parser.add_argument(
        "--output",
        default="firewall-backup",
        help="Output directory",
    )

    parser.add_argument(
        "--workers",
        type=int,
        default=3,
        help="Number of simultaneous firewall backups",
    )

    parser.add_argument(
        "--verify-ssl",
        action="store_true",
        help="Verify firewall TLS certificates",
    )

    args = parser.parse_args()

    if not args.username:

        print(
            "ERROR: username required.\n"
            "Use --username or PAN_USER.",
            file=sys.stderr,
        )

        sys.exit(1)

    password = getpass.getpass(
        f"Password for '{args.username}': "
    )

    firewalls = read_firewall_list(
        args.firewall_file
    )

    if not firewalls:

        print(
            "No firewalls found.",
            file=sys.stderr,
        )

        sys.exit(1)

    output_dir = Path(args.output)
    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    date_string = datetime.now().strftime(
        "%Y-%m-%d"
    )

    print()
    print("=" * 70)
    print("FIREWALL XML BACKUP")
    print("=" * 70)
    print(f"Input    : {args.firewall_file}")
    print(f"Firewalls: {len(firewalls)}")
    print(f"Workers  : {args.workers}")
    print(f"Output   : {output_dir.resolve()}")
    print()

    results = []

    with ThreadPoolExecutor(
        max_workers=args.workers
    ) as executor:

        futures = {
            executor.submit(
                backup_firewall,
                firewall,
                args.username,
                password,
                output_dir,
                date_string,
                args.verify_ssl,
            ): firewall
            for firewall in firewalls
        }

        for future in as_completed(futures):

            result = future.result()

            results.append(result)

            if result["success"]:

                print(
                    f"OK   {result['hostname']:<30} "
                    f"{result['file']}"
                )

            else:

                print(
                    f"FAIL {result['hostname']:<30} "
                    f"{result['error']}",
                    file=sys.stderr,
                )

    successful = sum(
        1 for r in results if r["success"]
    )

    failed = len(results) - successful

    print()
    print("=" * 70)
    print("COMPLETE")
    print("=" * 70)
    print(f"Successful: {successful}")
    print(f"Failed    : {failed}")
    print(f"Output    : {output_dir.resolve()}")
    print()


if __name__ == "__main__":
    main()
