#!/usr/bin/env python3

import argparse
import urllib.parse
import boto3

parser = argparse.ArgumentParser(description="List AWS Organization accounts")
parser.add_argument("--profile", help="AWS CLI profile")
parser.add_argument(
    "--role",
    default="OrganizationAccountAccessRole",
    help="Role name for Switch Role links"
)
args = parser.parse_args()

if args.profile:
    session = boto3.Session(profile_name=args.profile)
else:
    session = boto3.Session()

org = session.client("organizations")


def get_root_id():
    return org.list_roots()["Roots"][0]["Id"]


def list_ous(parent_id):
    paginator = org.get_paginator("list_organizational_units_for_parent")
    ous = []
    for page in paginator.paginate(ParentId=parent_id):
        ous.extend(page["OrganizationalUnits"])
    return ous


def list_accounts(parent_id):
    paginator = org.get_paginator("list_accounts_for_parent")
    accounts = []
    for page in paginator.paginate(ParentId=parent_id):
        accounts.extend(page["Accounts"])
    return accounts


rows = []


def walk(parent_id, path):
    for acct in list_accounts(parent_id):
        switch_url = (
            "https://signin.aws.amazon.com/switchrole?"
            f"account={acct['Id']}"
            f"&roleName={urllib.parse.quote(args.role)}"
            f"&displayName={urllib.parse.quote(acct['Name'])}"
        )

        rows.append({
            "ou": path,
            "name": acct["Name"],
            "id": acct["Id"],
            "url": switch_url,
        })

    for ou in list_ous(parent_id):
        walk(ou["Id"], f"{path}/{ou['Name']}")


walk(get_root_id(), "Root")

rows.sort(key=lambda r: (r["ou"], r["name"]))

ou_width = max(len(r["ou"]) for r in rows)
name_width = max(len(r["name"]) for r in rows)

print(
    f'{"OU":<{ou_width}}  '
    f'{"Account Name":<{name_width}}  '
    f'{"Account ID":12}  '
    f'Switch Role URL'
)

print("-" * (ou_width + name_width + 110))

for r in rows:
    print(
        f'{r["ou"]:<{ou_width}}  '
        f'{r["name"]:<{name_width}}  '
        f'{r["id"]}  '
        f'{r["url"]}'
    )
